baseURL = 'https://yethingchan/yethingchan.github.io/'
locale = 'zh-CN'
title = ' Odyssey Blog'
theme = 'hugo-PaperMod-master'
copyright = 'Yethingchan'
[[menu.main]]
  name = "首页"
  url = "/"
  weight = 1  # 权重越小，排序越靠前
 
[[menu.main]]
  name = "文章"
  url = "/posts/"
  weight = 2
 
[[menu.main]]
  name = "关于"
  url = "/about/"
  weight = 3